topo:
	sudo python myTopo.py
clean:
	sudo pkill python
	sudo mn -c

#There is no need to run testing file. The myTopo file will start the network topo and the testing function automatically and print the result of test on the screen.Controller should start at first.
